name: CI Base Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25

    - uses: gradle/actions/setup-gradle@v5

